# TF data records and dataset creation  + TF Data API

## Exemplo simples
#### O que é a classe "dataset" do TF
## ver https://www.tensorflow.org/guide/data
### Criação deste tipo de dados com tf.data.Dataset.from_tensor_slices() ou só "from_tensor"

Carregar as bibs

In [2]:
import numpy as np
import numpy.random as rd
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras as keras
from time import time
import cv2
import os
import pickle

#para usar GPU
gp=tf.config.list_physical_devices('GPU')
print(gp)
if len(gp)!=0:
    tf.config.experimental.set_memory_growth(gp[0],True)

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


#### Criar gerador a partir de tensor (range)

In [2]:
a=tf.range(10)
print(a)
print(type(a))

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [2]:
X=tf.range(10)
print(X)
DT=tf.data.Dataset.from_tensor_slices(X)
# or DT=tf.dataDatase.range(10)
print(DT)
for i in DT:
    print(i)


tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
<TensorSliceDataset shapes: (), types: tf.int32>
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [3]:
#tensor com 3 elementos por slice
X=tf.convert_to_tensor(rd.randint(0,10,(3,5),dtype='int32'))
print(X)
DT=tf.data.Dataset.from_tensor_slices(X)
print(DT)
for i in DT:
    print(i)


tf.Tensor(
[[4 5 5 8 9]
 [6 7 3 0 5]
 [3 2 4 2 3]], shape=(3, 5), dtype=int32)
<TensorSliceDataset shapes: (5,), types: tf.int32>
tf.Tensor([4 5 5 8 9], shape=(5,), dtype=int32)
tf.Tensor([6 7 3 0 5], shape=(5,), dtype=int32)
tf.Tensor([3 2 4 2 3], shape=(5,), dtype=int32)


#### Usar comando $\texttt{take}$ para ver só uns quantos itens

In [4]:
X=tf.range(10)
print(X)
DT=tf.data.Dataset.from_tensor_slices(X)
print(DT)
for i in DT.take(3):
    print(i)


tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
<TensorSliceDataset shapes: (), types: tf.int32>
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [5]:
X=tf.range(10)
print(X)
DT=tf.data.Dataset.from_tensor_slices(X)
for i in range(4):
    for j in DT.take(3):
        print(j)


tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


#### Dataset as a Python iterator - using the $\texttt{next()}$ function

In [6]:
#python iterators
X=tf.range(10)
print(X)
DT=tf.data.Dataset.from_tensor_slices(X)
print(DT)
it=iter(DT)
print(it)
print(next(it))
print(next(it))

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
<TensorSliceDataset shapes: (), types: tf.int32>
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [9]:
X=tf.range(10)
print(X)
DT=tf.data.Dataset.from_tensor_slices(X)
print(DT)
it=iter(DT)
# Error when N>10
N=10
for i in range(N):
    print(next(it))

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
<TensorSliceDataset shapes: (), types: tf.int32>
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


### Other dataset creation functions

In [58]:
#processing lines from files
f1=open('file1.txt')
print(str(f1.read()))
f1.close()
f2=open('file2.txt')
print(str(f2.read()))
f2.close()

DT= tf.data.TextLineDataset(["file1.txt", "file2.txt"])
#DT= tf.data.TextLineDataset(["CaliforniaHousing.csv"])
for l in DT:
    print(l.numpy().decode())


Because I could not stop for Death,
He kindly stopped for me;
The carriage held but just ourselves
And Immortality.

I'm nobody! Who are you?
Are you nobody, too?
Then there's a pair of us - don't tell!
They'd banish us, you know.
How dreary to be somebody!
How public, like a frog
To tell your name the livelong day
To an admiring bog!

Because I could not stop for Death,
He kindly stopped for me;
The carriage held but just ourselves
And Immortality.
I'm nobody! Who are you?
Are you nobody, too?
Then there's a pair of us - don't tell!
They'd banish us, you know.
How dreary to be somebody!
How public, like a frog
To tell your name the livelong day
To an admiring bog!


### Chaining Transformations

#### O código anterior pode ser feito encadeando comandos 

In [35]:
DT=tf.data.Dataset.range(10).repeat(2).batch(6)
print('**********1st****************')
[print(i) for i in DT]
    
    
print('**********2nd****************')
DT=tf.data.Dataset.range(10).batch(6).repeat(2)
[print(i) for i in DT]


**********1st****************
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
tf.Tensor([6 7 8 9 0 1], shape=(6,), dtype=int64)
tf.Tensor([2 3 4 5 6 7], shape=(6,), dtype=int64)
tf.Tensor([8 9], shape=(2,), dtype=int64)
**********2nd****************
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
tf.Tensor([6 7 8 9], shape=(4,), dtype=int64)
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
tf.Tensor([6 7 8 9], shape=(4,), dtype=int64)


[None, None, None, None]

### Use shuffle before batch

In [45]:
DT=tf.data.Dataset.range(5).repeat(3).batch(6).shuffle(buffer_size=5)
print('**********1st****************')
[print(i) for i in DT]
    
    
DT=tf.data.Dataset.range(5).repeat(3).shuffle(buffer_size=5).batch(6)
print('**********2nd****************')
[print(i) for i in DT]

DT=tf.data.Dataset.range(5).shuffle(buffer_size=5).repeat(3).batch(6)
print('**********3rd****************')
[print(i) for i in DT]


**********1st****************
tf.Tensor([0 1 2 3 4 0], shape=(6,), dtype=int64)
tf.Tensor([2 3 4], shape=(3,), dtype=int64)
tf.Tensor([1 2 3 4 0 1], shape=(6,), dtype=int64)
**********2nd****************
tf.Tensor([1 4 0 2 2 3], shape=(6,), dtype=int64)
tf.Tensor([0 0 2 1 3 4], shape=(6,), dtype=int64)
tf.Tensor([4 3 1], shape=(3,), dtype=int64)
**********3rd****************
tf.Tensor([0 3 4 2 1 0], shape=(6,), dtype=int64)
tf.Tensor([4 2 3 1 3 2], shape=(6,), dtype=int64)
tf.Tensor([0 1 4], shape=(3,), dtype=int64)


[None, None, None]

In [18]:
batchS=12
DT=tf.data.Dataset.range(10).repeat(3).batch(batchS).shuffle(buffer_size=10)
for i in DT:
    print(i)

tf.Tensor([4 5 6 7 8 9], shape=(6,), dtype=int64)
tf.Tensor([0 1 2 3 4 5 6 7 8 9 0 1], shape=(12,), dtype=int64)
tf.Tensor([2 3 4 5 6 7 8 9 0 1 2 3], shape=(12,), dtype=int64)


In [19]:
#baralhar (necessário recomeçar)
DT=tf.data.Dataset.range(10).repeat(3).shuffle(buffer_size=10,seed=42).batch(batchS)
#DT=DT.shuffle(buffer_size=10,seed=42).batch(batchS)
for i in DT:
    print(i)


tf.Tensor([5 2 8 1 7 9 2 0 0 4 6 3], shape=(12,), dtype=int64)
tf.Tensor([1 0 9 3 7 6 7 8 3 4 6 8], shape=(12,), dtype=int64)
tf.Tensor([4 1 5 9 5 2], shape=(6,), dtype=int64)


#### Com .repeat() o gerador não para

In [20]:
DT=tf.data.Dataset.range(10).shuffle(buffer_size=10,seed=42).batch(batchS).repeat()

for i,x in enumerate(DT):
    print(x)
    if i>10:
        break

tf.Tensor([5 9 6 4 7 1 2 8 3 0], shape=(10,), dtype=int64)
tf.Tensor([3 7 6 5 8 4 0 1 9 2], shape=(10,), dtype=int64)
tf.Tensor([2 8 9 6 0 4 1 3 5 7], shape=(10,), dtype=int64)
tf.Tensor([6 9 0 5 3 2 4 1 8 7], shape=(10,), dtype=int64)
tf.Tensor([9 5 1 8 7 4 3 0 2 6], shape=(10,), dtype=int64)
tf.Tensor([4 7 8 1 9 0 6 5 3 2], shape=(10,), dtype=int64)
tf.Tensor([2 1 6 8 3 0 7 4 5 9], shape=(10,), dtype=int64)
tf.Tensor([2 7 9 1 8 5 6 3 0 4], shape=(10,), dtype=int64)
tf.Tensor([7 9 0 6 2 3 5 1 8 4], shape=(10,), dtype=int64)
tf.Tensor([0 9 2 5 6 3 7 8 1 4], shape=(10,), dtype=int64)
tf.Tensor([1 4 0 6 9 5 3 8 2 7], shape=(10,), dtype=int64)
tf.Tensor([1 4 2 6 7 8 3 5 9 0], shape=(10,), dtype=int64)


#### Aceder aos elementos de DT:
#### Notar que DT são só 3 tensores - take(n) com n>3 não altera resultado
#### Mas pode-se chamar várias vezes e dá tensores diferentes

In [203]:
for n in range(3):
    for r in DT.take(5):
        print(r)
    print('-')

tf.Tensor([2 3 4 5 6 7 8 9 0 1 2 3], shape=(12,), dtype=int64)
tf.Tensor([4 5 6 7 8 9], shape=(6,), dtype=int64)
tf.Tensor([0 1 2 3 4 5 6 7 8 9 0 1], shape=(12,), dtype=int64)
-
tf.Tensor([4 5 6 7 8 9], shape=(6,), dtype=int64)
tf.Tensor([2 3 4 5 6 7 8 9 0 1 2 3], shape=(12,), dtype=int64)
tf.Tensor([0 1 2 3 4 5 6 7 8 9 0 1], shape=(12,), dtype=int64)
-
tf.Tensor([2 3 4 5 6 7 8 9 0 1 2 3], shape=(12,), dtype=int64)
tf.Tensor([4 5 6 7 8 9], shape=(6,), dtype=int64)
tf.Tensor([0 1 2 3 4 5 6 7 8 9 0 1], shape=(12,), dtype=int64)
-


#### Criar e ler um simples dataset

### Criar um gerador 

In [158]:
#criar gerador de três elementos
def arrayInt():
    return rd.randint(-2**15,2**15,size=4,dtype='int16')

def matrixUint():
    return rd.randint(0,255,size=(3,3),dtype='uint8')

def arrayFloat():
    return rd. randn(5).astype(np.float32)

def generator():
    #deitar continuamente
    while(True):
        a=arrayInt()
        M=matrixUint()
        f=arrayFloat()
        
        yield a,M,f

In [161]:
c=0
for a,M,f in generator():
    c+=1
    print(a)
    print(M)
    print(f)
    if c>5:
        break

print(c)                      

[-9664  1814 16082 -5422]
[[174 121 225]
 [183 189   9]
 [ 69 175  16]]
[-1.0999719   0.11372941  1.5592335  -0.40443957 -0.93626505]
[31978 -6440 20259 15913]
[[177 191 165]
 [107  60 182]
 [ 97  80  73]]
[-1.219581    0.6939774  -0.5321984  -0.55153555 -0.7087945 ]
[ 14957  31681  27183 -30740]
[[208 156 161]
 [ 16 160  13]
 [103  32 102]]
[0.75400746 0.4059997  0.21547839 0.3382673  0.35364875]
[21245 -3219 -3164 25968]
[[204 154  27]
 [110  56 212]
 [ 17  47   2]]
[-0.77188593 -0.5023383  -0.02088019  0.3830908   1.7038862 ]
[ 13650  -9724   8775 -15946]
[[124 216 235]
 [161 142  62]
 [129  32 179]]
[ 0.46829972  1.9050341  -0.7707365  -0.31116116 -0.04753039]
[-19367  30382  25698  28629]
[[150  40  19]
 [ 12 168 254]
 [243 135  69]]
[-0.5030424   0.3905247  -0.32169467  0.3690189   0.42744833]
6


#### TF Generator

In [162]:
DT=tf.data.Dataset.from_generator(generator,(tf.int16,tf.uint8,tf.float32),((4,),(3,3),(5,)))
DT2=DT.batch(1)
for a,M,f in DT.take(4):
    print(a)
    print(M)
    print(f)

tf.Tensor([-27762   4119 -21466   9569], shape=(4,), dtype=int16)
tf.Tensor(
[[181 114 159]
 [ 87 103 125]
 [ 98  80 147]], shape=(3, 3), dtype=uint8)
tf.Tensor([-0.13291968  0.67417353  0.2437165  -1.2371067  -1.1164429 ], shape=(5,), dtype=float32)
tf.Tensor([-15943 -12276  -9545  -9070], shape=(4,), dtype=int16)
tf.Tensor(
[[220 248 192]
 [106  62 251]
 [164  23 186]], shape=(3, 3), dtype=uint8)
tf.Tensor([ 0.02280253  0.8596388   1.1581112   0.5963715  -0.1857946 ], shape=(5,), dtype=float32)
tf.Tensor([25169  -502 14755 -9987], shape=(4,), dtype=int16)
tf.Tensor(
[[ 98   8   5]
 [105 132 102]
 [196 151  56]], shape=(3, 3), dtype=uint8)
tf.Tensor([ 1.1551803  -0.65935916 -1.921149   -0.6476706  -0.03043949], shape=(5,), dtype=float32)
tf.Tensor([ 11082 -20151 -25111 -20970], shape=(4,), dtype=int16)
tf.Tensor(
[[ 25 190 173]
 [175  75 124]
 [ 47  27 223]], shape=(3, 3), dtype=uint8)
tf.Tensor([ 1.0355753   0.09367475  0.26215106 -0.24967682 -0.01290622], shape=(5,), dtype=float32)


## Data transformations
### map(), filter() and apply() functions

In [10]:
#DT= tf.data.Dataset.range(10).shuffle(10,reshuffle_each_iteration=False,seed=42).repeat(3).batch(5)
DT= tf.data.Dataset.range(10).repeat(3).batch(5)
for l in DT:
    print(l.numpy())
DT=DT.map(lambda x :x*(x%2))
print('\n')
for l in DT:
    print(l.numpy())

[0 1 2 3 4]
[5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]


[0 1 0 3 0]
[5 0 7 0 9]
[0 1 0 3 0]
[5 0 7 0 9]
[0 1 0 3 0]
[5 0 7 0 9]


In [7]:
def odd_a(x):
    print(tf.executing_eagerly())
    return x*(x%2)

def odd_b(x):
    print(tf.executing_eagerly())
    x=tf.math.multiply(x,tf.math.floormod(x,2))
    return x

#@tf.function
def odd_c(x):
    print(tf.executing_eagerly())
    x=x*(np.remainder(x,2))
    #return tf.Tensor(x) #dá erro!
    return tf.convert_to_tensor(x) #já não dá!

@tf.function
def wrapper(x):
    #x=odd_a(x)

    tf.py_function(func=odd_a,inp=[x],Tout=[tf.int64]) 
    #tf.function(odd_b)
    return x

DT= tf.data.Dataset.range(10).repeat(3).batch(5)
#for l in DT:
#    print(l.numpy())

DTa=DT.map(odd_a)
print('\na:\n')
for l in DTa:
    print(l.numpy())

DTb=DT.map(odd_b)
print('\nb:\n')
for l in DTb:
    print(l.numpy())

DTc=DT.map(wrapper) #bad! -> com odd_a ou odd_b não se queixa mas não tira valores pares!!!
print('\nc:\n')
for l in DTc:
    print(l.numpy())

#x=tf.Tensor([0,0,0,0,0],dtype='int64')
#x=tf.Variable([0,0,0,0,0],dtype='int64')
#x=np.array([0,0,0,0,0],dtype='int64')
#x=tf.compat.v1.placeholder(tf.int64)
#odd_d=tf.py_function(func=odd_d,inp=[x],Tout=[tf.int64])



False

a:

[0 1 0 3 0]
[5 0 7 0 9]
[0 1 0 3 0]
[5 0 7 0 9]
[0 1 0 3 0]
[5 0 7 0 9]
False

b:

[0 1 0 3 0]
[5 0 7 0 9]
[0 1 0 3 0]
[5 0 7 0 9]
[0 1 0 3 0]
[5 0 7 0 9]

c:

True
[0 1 2 3 4]
True
[5 6 7 8 9]
True
[0 1 2 3 4]
True
[5 6 7 8 9]
True
[0 1 2 3 4]
True
[5 6 7 8 9]


In [7]:
for i in DTc:
    print(i)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)


In [35]:
def odd_A(x):
    x=x*(x%2)
    return x

def odd_B(x):
    x=tf.math.multiply(tf.math.floormod(x,2),x)
    return x
@tf.function
def odd_C(x):
    return tf.math.multiply(tf.math.floormod(x,2),x)


#Assim não dá.  TF->Numpy proibido
def odd_D(x):
    x=x*(np.remainder(x,2))
    return x

#Assim já dá!!! NÃO: voltou a não dar!?!?!
def odd_E(x):
    x=tf.convert_to_tensor(x*(np.remainder(x,2)))
    return x

DT= tf.data.Dataset.range(10).repeat(3).batch(5)

for l in DT:
    print(l.numpy())

odd=odd_E
st=time()
DTa=DT.map(odd)
et=time()
print(et-st)
print('\na:\n')
for l in DTa:
    print(l.numpy())


#Assim não dá - algo a haver com eager mode...
#DTb=DT.map(tf.py_function(func=odd_C,inp=[tf.int32],Tout=[tf.int32]))
#print('\nb:\n')
#for l in DTb:
#    print(l.numpy())




[0 1 2 3 4]
[5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]


NotImplementedError: in user code:

    <ipython-input-35-5332fcf02362>:20 odd_E  *
        x=tf.convert_to_tensor(x*(np.remainder(x,2)))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:870 __array__  **
        " a NumPy call, which is not supported".format(self.name))

    NotImplementedError: Cannot convert a symbolic Tensor (args_0:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
